version: "3.8"
services:
  app:
    build: .
    ports:
      - "3000:3000"
    command: yarn start
    working_dir: /app
    volumes:
      - ./:/usr/src/app
      - node_modules:/usr/src/app/node_modules
volumes:
  node_modules: