import { Category } from "@/types/category";

// NYT Api does not provide a endpoint for getting the categories, but they provided a list of each possible value
export const nytCategories: Category[] = [
  { id: "Adventure Sports", name: "Adventure Sports", apiSource: "NYT" },
  { id: "Arts & Leisure", name: "Arts & Leisure", apiSource: "NYT" },
  { id: "Arts", name: "Arts", apiSource: "NYT" },
  { id: "Automobiles", name: "Automobiles", apiSource: "NYT" },
  { id: "Blogs", name: "Blogs", apiSource: "NYT" },
  { id: "Books", name: "Books", apiSource: "NYT" },
  { id: "Booming", name: "Booming", apiSource: "NYT" },
  { id: "Business Day", name: "Business Day", apiSource: "NYT" },
  { id: "Business", name: "Business", apiSource: "NYT" },
  { id: "Cars", name: "Cars", apiSource: "NYT" },
  { id: "Circuits", name: "Circuits", apiSource: "NYT" },
  { id: "Classifieds", name: "Classifieds", apiSource: "NYT" },
  { id: "Connecticut", name: "Connecticut", apiSource: "NYT" },
  { id: "Crosswords & Games", name: "Crosswords & Games", apiSource: "NYT" },
  { id: "Culture", name: "Culture", apiSource: "NYT" },
  { id: "DealBook", name: "DealBook", apiSource: "NYT" },
  { id: "Dining", name: "Dining", apiSource: "NYT" },
  { id: "Editorial", name: "Editorial", apiSource: "NYT" },
  { id: "Education", name: "Education", apiSource: "NYT" },
  { id: "Energy", name: "Energy", apiSource: "NYT" },
  { id: "Entrepreneurs", name: "Entrepreneurs", apiSource: "NYT" },
  { id: "Environment", name: "Environment", apiSource: "NYT" },
  { id: "Escapes", name: "Escapes", apiSource: "NYT" },
  { id: "Fashion & Style", name: "Fashion & Style", apiSource: "NYT" },
  { id: "Fashion", name: "Fashion", apiSource: "NYT" },
  { id: "Favorites", name: "Favorites", apiSource: "NYT" },
  { id: "Financial", name: "Financial", apiSource: "NYT" },
  { id: "Flight", name: "Flight", apiSource: "NYT" },
  { id: "Food", name: "Food", apiSource: "NYT" },
  { id: "Foreign", name: "Foreign", apiSource: "NYT" },
  { id: "Generations", name: "Generations", apiSource: "NYT" },
  { id: "Giving", name: "Giving", apiSource: "NYT" },
  { id: "Global Home", name: "Global Home", apiSource: "NYT" },
  { id: "Health & Fitness", name: "Health & Fitness", apiSource: "NYT" },
  { id: "Health", name: "Health", apiSource: "NYT" },
  { id: "Home & Garden", name: "Home & Garden", apiSource: "NYT" },
  { id: "Home", name: "Home", apiSource: "NYT" },
  { id: "Jobs", name: "Jobs", apiSource: "NYT" },
  { id: "Key", name: "Key", apiSource: "NYT" },
  { id: "Letters", name: "Letters", apiSource: "NYT" },
  { id: "Long Island", name: "Long Island", apiSource: "NYT" },
  { id: "Magazine", name: "Magazine", apiSource: "NYT" },
  { id: "Market Place", name: "Market Place", apiSource: "NYT" },
  { id: "Media", name: "Media", apiSource: "NYT" },
  { id: "Men's Health", name: "Men's Health", apiSource: "NYT" },
  { id: "Metro", name: "Metro", apiSource: "NYT" },
  { id: "Metropolitan", name: "Metropolitan", apiSource: "NYT" },
  { id: "Movies", name: "Movies", apiSource: "NYT" },
  { id: "Museums", name: "Museums", apiSource: "NYT" },
  { id: "National", name: "National", apiSource: "NYT" },
  { id: "Nesting", name: "Nesting", apiSource: "NYT" },
  { id: "Obits", name: "Obits", apiSource: "NYT" },
  { id: "Obituaries", name: "Obituaries", apiSource: "NYT" },
  { id: "Obituary", name: "Obituary", apiSource: "NYT" },
  { id: "OpEd", name: "OpEd", apiSource: "NYT" },
  { id: "Opinion", name: "Opinion", apiSource: "NYT" },
  { id: "Outlook", name: "Outlook", apiSource: "NYT" },
  { id: "Personal Investing", name: "Personal Investing", apiSource: "NYT" },
  { id: "Personal Tech", name: "Personal Tech", apiSource: "NYT" },
  { id: "Play", name: "Play", apiSource: "NYT" },
  { id: "Politics", name: "Politics", apiSource: "NYT" },
  { id: "Regionals", name: "Regionals", apiSource: "NYT" },
  { id: "Retail", name: "Retail", apiSource: "NYT" },
  { id: "Retirement", name: "Retirement", apiSource: "NYT" },
  { id: "Science", name: "Science", apiSource: "NYT" },
  { id: "Small Business", name: "Small Business", apiSource: "NYT" },
  { id: "Society", name: "Society", apiSource: "NYT" },
  { id: "Sports", name: "Sports", apiSource: "NYT" },
  { id: "Style", name: "Style", apiSource: "NYT" },
  { id: "Sunday Business", name: "Sunday Business", apiSource: "NYT" },
  { id: "Sunday Review", name: "Sunday Review", apiSource: "NYT" },
  { id: "Sunday Styles", name: "Sunday Styles", apiSource: "NYT" },
  { id: "T Magazine", name: "T Magazine", apiSource: "NYT" },
  { id: "T Style", name: "T Style", apiSource: "NYT" },
  { id: "Technology", name: "Technology", apiSource: "NYT" },
  { id: "Teens", name: "Teens", apiSource: "NYT" },
  { id: "Television", name: "Television", apiSource: "NYT" },
  { id: "The Arts", name: "The Arts", apiSource: "NYT" },
  {
    id: "The Business of Green",
    name: "The Business of Green",
    apiSource: "NYT",
  },
  { id: "The City Desk", name: "The City Desk", apiSource: "NYT" },
  { id: "The City", name: "The City", apiSource: "NYT" },
  { id: "The Marathon", name: "The Marathon", apiSource: "NYT" },
  { id: "The Millennium", name: "The Millennium", apiSource: "NYT" },
  { id: "The Natural World", name: "The Natural World", apiSource: "NYT" },
  { id: "The Upshot", name: "The Upshot", apiSource: "NYT" },
  { id: "The Weekend", name: "The Weekend", apiSource: "NYT" },
  {
    id: "The Year in Pictures",
    name: "The Year in Pictures",
    apiSource: "NYT",
  },
  { id: "Theater", name: "Theater", apiSource: "NYT" },
  { id: "Then & Now", name: "Then & Now", apiSource: "NYT" },
  { id: "Thursday Styles", name: "Thursday Styles", apiSource: "NYT" },
  { id: "Times Topics", name: "Times Topics", apiSource: "NYT" },
  { id: "Travel", name: "Travel", apiSource: "NYT" },
  { id: "U.S.", name: "U.S.", apiSource: "NYT" },
  { id: "Universal", name: "Universal", apiSource: "NYT" },
  { id: "Upshot", name: "Upshot", apiSource: "NYT" },
  { id: "UrbanEye", name: "UrbanEye", apiSource: "NYT" },
  { id: "Vacation", name: "Vacation", apiSource: "NYT" },
  { id: "Washington", name: "Washington", apiSource: "NYT" },
  { id: "Wealth", name: "Wealth", apiSource: "NYT" },
  { id: "Weather", name: "Weather", apiSource: "NYT" },
  { id: "Week in Review", name: "Week in Review", apiSource: "NYT" },
  { id: "Week", name: "Week", apiSource: "NYT" },
  { id: "Weekend", name: "Weekend", apiSource: "NYT" },
  { id: "Westchester", name: "Westchester", apiSource: "NYT" },
  { id: "Wireless Living", name: "Wireless Living", apiSource: "NYT" },
  { id: "Women's Health", name: "Women's Health", apiSource: "NYT" },
  { id: "Working", name: "Working", apiSource: "NYT" },
  { id: "Workplace", name: "Workplace", apiSource: "NYT" },
  { id: "World", name: "World", apiSource: "NYT" },
  { id: "Your Money", name: "Your Money", apiSource: "NYT" },
];
